# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4f315570-b85f-4dbf-8eac-7f17a3a7a054";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-4f315570-b85f-4dbf-8eac-7f17a3a7a054".device = "/dev/disk/by-uuid/4f315570-b85f-4dbf-8eac-7f17a3a7a054";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-4f315570-b85f-4dbf-8eac-7f17a3a7a054";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-4f315570-b85f-4dbf-8eac-7f17a3a7a054";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/36CC-66FF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-841e7165-c5f2-480c-a938-bcaa36cb817c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
